name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: interview-ai-84058

      - name: Build & Push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/interview-ai-84058/flask-app .
          docker push gcr.io/interview-ai-84058/flask-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/interview-ai-84058/flask-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS=/app/config/key.json,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }},SECRET_KEY=${{ secrets.SECRET_KEY }},SQLALCHEMY_DATABASE_URI=sqlite:///app.db,KAFKA_BROKER=localhost:9092,KAFKA_TOPIC_AUDIO=audio_stream,KAFKA_TOPIC_VIDEO=video_stream,KAFKA_TOPIC_TRANSCRIPT=transcript_results,KAFKA_TOPIC_EMOTION=emotion_results"
